apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-qykv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-qykv
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-qykv
  namespace: e2e-demos-pvfv-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-qykv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-qykv
    spec:
      containers:
      - image: quay.io/psturc/test-images-protected@sha256:7fb7006d225a924b000c892e8bd3b3294088b35a87c2d37009fbd24e3d2508d6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
